### ISSUE TITLE
Vertical progress bar moving horizontal on safari mobile

### ISSUE THREAD

**Issue by ssuess** [glarios/jQMeter#2]
thanks for this plugin works great except in mobile safari (and mobile chrome for that matter) the vertical progress bar is moving horizontally (works great everywhere else on desktop browsers). Any suggestions?

**Comment by ssuess** [comment]
just checked and same thing happens in your demo: http://www.jqueryscript.net/demo/Animated-Customizable-Progress-Meter-Plugin-For-jQuery-jQMeter/

**Comment by glarios** [comment]
Thanks for your feedback Stephen. I will look into a fix for this and let you know once it's resolved.

**Comment by ssuess** [comment]
Thanks!

**Comment by pankajmehra009** [comment]
Is this issue solved yet , I have tried this on mobile browser and results are same.

Thanks

**Comment by ssuess** [comment]
I haven't seen any code updates since I posted it, so I don't think it is solved yet, no. I have tried to look at the code myself to figure out what is causing it, but so far I am stumped as to why it only fails on mobile browsers.

**Comment by glarios** [comment]
Sorry for the delay guys. I've been super busy. I just fixed the issue. I was using "orientation" as a variable name but that is a reserved name in mobile. Please use the newest release.

**Comment by ssuess** [comment]
Thanks for the update, but this new code actually breaks everywhere, on both mobile and desktop. The same thing that was happening only on mobile before is now happening on both mobile and desktop for me. Meaning: I have a vertical bar whose progress indicator is moving horizontally across it.

**Comment by glarios** [comment]
ssuess, can you provide a link? Did you update your plugin instatiation options to include meterOrientation instead of orientation?

**Comment by ssuess** [comment]
no, I just replaced the min.js file...I'm sorry do I also need to make config changes?

**Comment by glarios** [comment]
Yes, the "orientation" option needs to be "meterOrientation" now

**Comment by ssuess** [comment]
Sorry let me try that and get back to you...

**Comment by glarios** [comment]
So for example, it should be like this:

 $('#jqmeter-container').jQMeter({meterOrientation:'vertical'});

**Comment by ssuess** [comment]
fixed! Thanks!!!

**Comment by ssuess** [comment]
but that should probably go in the docs, it still says "orientation" there...

**Comment by glarios** [comment]
Yes, updating now.
