### ISSUE TITLE
Dynamically increase the value raised

### ISSUE THREAD

**Issue by bjonamu** [glarios/jQMeter#3]
JQMeter is very nice and quite handy. Is it possible to increase the value raised dynamically?

**Comment by glarios** [comment]
Hi Jonrock23, you should be able to pass it as a variable into the plugin options. Example:

var dynamicRaised=(Populate this variable dynamically, then pass it as an argument).

$('#jqmeter-container').jQMeter({
    goal:'$1,000',
    raised:dynamicRaised
});
