### ISSUE TITLE
Issue passing variables into goal and raised parameters

### ISSUE THREAD

**Issue by symbiontsynth** [glarios/jQMeter#4]
The plugin works great if I hardcode the values for goal and raised. However, if I try to pass a variable, the bars don't render at all. I've verified my two variables are producing the expected values. Not sure if I'm formatting it wrong, missed something obvious, or if the plugin just doesn't work with dynamic variables. Sample code below:

```
$(document).ready(function(){
var barGoal = /*dynamically determined*/;
var mathScore = /*dynamically determined*/;
    $('#mScore').jQMeter({
        goal:barGoal,
        raised:mathScore,
        meterOrientation: 'vertical',
        width: '25px',
        height: '100px',
        bgColor: '#ffffff',
        barColor: '#ff0000',
        displayTotal:false
    });
});
```

**Comment by glarios** [comment]
Hi @symbiontsynth,

Thanks for your message. It should work with passing variables just fine.
Would you mind sharing how the barGoal and mathScore variables in your
script are actually being populated? Or better yet, do you have a link where I can see the issue recreated?

Thanks,

Gerardo

**Comment by glarios** [comment]
@symbiontsynth just following back up, were you able to get your issue resolved?

**Comment by symbiontsynth** [comment]
Sorry for the delayed response here. I wasn't able to get it working with a js variable and ended up using a php workaround to insert the dynamic values at the appropriate places in the script. I think what was happening originally was the variables were getting passed as an array. Since they originate from my php session data anyway I figured I'd just have the php script define the values directly. Probably not the most elegant solution but it's working.

**Comment by glarios** [comment]
Gotcha, yea "goal" and "raised" only take strings, so passing an array wouldn't work. Glad you were able to figure out a way around it.
